language: php

php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true

services:
  - mysql
  - redis-server

before_script:
  - phpenv config-rm xdebug.ini
  - if [[ $TRAVIS_PHP_VERSION = 7.4 ]]; then git clone git://github.com/xdebug/xdebug.git && cd xdebug && git checkout 2.9.0 && phpize && ./configure --enable-xdebug && make && make install && echo "zend_extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && cd ..; fi
  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --prefer-dist
  - composer require --dev friendsofphp/php-cs-fixer
  - composer require --dev php-coveralls/php-coveralls
  - wget https://github.com/phpstan/phpstan/releases/download/0.11.19/phpstan.phar
  - chmod +x ./phpstan.phar
  - mkdir -p build/logs

script:
  - vendor/bin/php-cs-fixer fix -v --diff --dry-run --format txt
  - ./phpstan.phar analyze --level=max src/
  - vendor/bin/phpunit -c phpunit.xml.travis.dist
  - vendor/bin/php-coveralls -v --exclude-no-stmt

notifications:
  email: false
