version: '2'
services:
    app:
        build: .
        restart: always
        environment:
            APP_ENV: dev
            APP_SECRET: aae212068d961c1d0633d680fea91252
            DATABASE_URL: postgres://postgres:postgres@db:5432/postgres

    balancer:
        image: dockercloud/haproxy:latest
        restart: always
        ports:
            - 8080:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - app
        depends_on:
            - app

    db:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_USER: semarthris
            POSTGRES_PASSWORD: semarthris
            POSTGRES_DB: semarthris
        volumes:
            - ./database:/var/lib/postgresql/data:rw

    session:
        image: redis:alpine
        restart: always

    adminer:
        image: adminer
        restart: always
        ports:
            - 9999:8080