version: '2'
services:
    app:
        build: .
        environment:
            NGINX_WEBROOT: /semart/public
            APP_ENV: dev
            APP_SECRET: 2a46d7812648fc10df43fa9431d5f75d
            DATABASE_DRIVER: pdo_mysql
            DATABASE_SERVER_VERSION: 5.7
            DATABASE_CHARSET: utf8mb4
            DATABASE_URL: mysql://root:semart@db:3306/semart
            REDIS_URL: redis://session
        volumes:
            - .:/semart
        links:
            - session
            - db
        depends_on:
            - session

    balancer:
        image: dockercloud/haproxy:latest
        ports:
            - 9876:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - app
        depends_on:
            - app

    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: semart

    adminer:
        image: adminer:latest
        ports:
            - 6789:8080
        links:
            - db

    session:
        image: redis:alpine
