version: '2'
services:
    app:
        build: .
        environment:
            NGINX_WEBROOT: /semart/public
            APP_ENV: dev
            APP_SECRET: 2a46d7812648fc10df43fa9431d5f75d
            DATABASE_DRIVER: pdo_pgsql
            DATABASE_SERVER_VERSION: 9.5
            DATABASE_CHARSET: utf8
            DATABASE_URL: pgsql://semart:semart@db:5432/semart?sslmode=disable
            REDIS_URL: redis://session
        links:
            - db
            - session
        depends_on:
            - db
            - session

    balancer:
        image: dockercloud/haproxy:latest
        ports:
            - 8080:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - app
        depends_on:
            - app
            
    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: semart
            POSTGRES_PASSWORD: semart
            POSTGRES_DB: semart
        volumes:
            - ./database:/var/lib/postgresql/data:rw

    session:
        image: redis:alpine
